"use client"

export function SvgCanvas({ svg }: { svg: string }) {
  return (
    <div
      className="h-full w-full bg-white"
      // svg is generated by our own SVG agent (server-side), not user input
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}
